
/**************************************************************
 *	
 *	Crunch, 8 bit, 11025Hz,
 *	1 channel, 14589 bytes/channel
 *	Total Size: 1 * 14589 + 4 (header) = 14633 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\M3\Crunch.wav
 *	Time-stamp: Mon Dec 04 21:21:03 2017
 *	
 **************************************************************/

#ifndef __CRUNCHH__
#define __CRUNCHH__

#define CRUNCHFREQ 11025
#define CRUNCHLEN 14589

extern const unsigned char Crunch[14589];

#endif /* __CRUNCHH__ */
