
/**************************************************************
 *	
 *	IntroSong, 8 bit, 11025Hz,
 *	1 channel, 2241504 bytes/channel
 *	Total Size: 1 * 2241504 + 4 (header) = 2241548 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\M3\IntroSong.wav
 *	Time-stamp: Fri Nov 24 20:39:16 2017
 *	
 **************************************************************/

#ifndef __INTROSONGH__
#define __INTROSONGH__

#define INTROSONGFREQ 11025
#define INTROSONGLEN 2241504

extern const unsigned char IntroSong[2241504];

#endif /* __INTROSONGH__ */
