
/**************************************************************
 *	
 *	Jump, 8 bit, 11025Hz,
 *	1 channel, 3536 bytes/channel
 *	Total Size: 1 * 3536 + 4 (header) = 3580 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\Jump.wav
 *	Time-stamp: Thu Nov 30 20:52:10 2017
 *	
 **************************************************************/

#ifndef __JUMPH__
#define __JUMPH__

#define JUMPFREQ 11025
#define JUMPLEN 3536

extern const unsigned char Jump[3536];

#endif /* __JUMPH__ */
