
/**************************************************************
 *	
 *	LoseSong, 8 bit, 44100Hz,
 *	1 channel, 12754944 bytes/channel
 *	Total Size: 1 * 12754944 + 4 (header) = 12754988 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\M3\LoseSong.wav
 *	Time-stamp: Tue Dec 05 19:46:50 2017
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 44100
#define LOSESONGLEN 12754944

extern const unsigned char LoseSong[12754944];

#endif /* __LOSESONGH__ */
