
/**************************************************************
 *	
 *	MainSong, 8 bit, 11025Hz,
 *	1 channel, 2250423 bytes/channel
 *	Total Size: 1 * 2250423 + 4 (header) = 2250467 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\M3\MainSong.wav
 *	Time-stamp: Fri Nov 24 20:46:19 2017
 *	
 **************************************************************/

#ifndef __MAINSONGH__
#define __MAINSONGH__

#define MAINSONGFREQ 11025
#define MAINSONGLEN 2250423

extern const unsigned char MainSong[2250423];

#endif /* __MAINSONGH__ */
