
/**************************************************************
 *	
 *	PauseSong, 8 bit, 11025Hz,
 *	1 channel, 2391719 bytes/channel
 *	Total Size: 1 * 2391719 + 4 (header) = 2391763 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\M3\PauseSong.wav
 *	Time-stamp: Fri Nov 24 20:47:45 2017
 *	
 **************************************************************/

#ifndef __PAUSESONGH__
#define __PAUSESONGH__

#define PAUSESONGFREQ 11025
#define PAUSESONGLEN 2391719

extern const unsigned char PauseSong[2391719];

#endif /* __PAUSESONGH__ */
