
/**************************************************************
 *	
 *	Water, 8 bit, 11025Hz,
 *	2 channel, 6835 bytes/channel
 *	Total Size: 2 * 6835 + 4 (header) = 13714 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\Water.wav
 *	Time-stamp: Thu Nov 30 20:52:19 2017
 *	
 **************************************************************/

#ifndef __WATERH__
#define __WATERH__

#define WATERFREQ 11025
#define WATERLEN 6835

extern const unsigned char Water_c1[6835];
extern const unsigned char Water_c2[6835];

#endif /* __WATERH__ */
