
/**************************************************************
 *	
 *	WinSong, 8 bit, 11025Hz,
 *	1 channel, 2123944 bytes/channel
 *	Total Size: 1 * 2123944 + 4 (header) = 2123988 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Bree~\Documents\School\CS2261\BryannaLawton_FinalProject\M3\WinSong.wav
 *	Time-stamp: Fri Nov 24 20:47:24 2017
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 2123944

extern const unsigned char WinSong[2123944];

#endif /* __WINSONGH__ */
